FROM ubuntu:22.04

WORKDIR /opt/veraison

COPY ./proxy_attestation_server /opt/veraison/
COPY ./CACert.pem /opt/veraison/
COPY ./CAKey.pem /opt/veraison/

EXPOSE 8080
WORKDIR /opt/veraison/
CMD ["./proxy_attestation_server", "-l", "verifier:8080"]
