name: Proxy Attestation Service module

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Check formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then gofmt -d .; exit 1; fi;

      - name: Build
        run: go build 

      - name: Test
        run: |
          echo "building vts-service"
          go build -o ./vts/vts github.com/veraison/services/vts/cmd/vts-service
          echo "building provisioning-service"
          go build -o ./provisioning/provisioning github.com/veraison/services/provisioning/cmd/provisioning-service
          go build -o ./provisioning/plugins/corim-psa-decoder github.com/veraison/services/provisioning/plugins/corim-psa-decoder
          go build -o ./provisioning/plugins/corim-nitro-decoder github.com/veraison/services/provisioning/plugins/corim-nitro-decoder
          go build -o ./vts/plugins/scheme-psa-iot github.com/veraison/services/vts/plugins/scheme-psa-iot
          go build -o ./vts/plugins/scheme-aws-nitro github.com/veraison/services/vts/plugins/scheme-aws-nitro
          go test
